package org.ppsim.config;

import org.apache.log4j.Logger;

import java.io.FileNotFoundException;

/**
 * Helper class used to parse user defined configuration properties.
 */
public class ConfigurationParser {
    /**
     * a log4j logger to print messages.
     */
    protected static final Logger LOGGER = Logger.getLogger(ConfigurationParser.class);

    /**
     * Parses a config file and returns the setup information for the experiment to execute.
     *
     * @param fileName the name of the file to use as configuration.
     * @return the ConfigFile object generated by the configuration file.
     * @throws FileNotFoundException
     */
    public static ConfigFile parseConfigFile(final String fileName) throws FileNotFoundException {
        return new ConfigFile(fileName);
    }
}
